### PR TITLE
google_sheets.py

### PR DESCRIPTION
**Pull request by TangoYankee**
#Sheets API Requires a Google Cloud services account.
#Instructions are found in this link
#http://gspread.readthedocs.io/en/latest/oauth2.html

import gspread
import datetime
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds'] #Sheet must be shared with Cloud account in order to find it
validation ="" #Validation pulls from JSON account information file
sheet_key = "" #Key from sheet URL
top_row = 2 #First Row is header #Limited ability to find the end of the data. Easier just to put data at the top and find it later

credentials = ServiceAccountCredentials.from_json_keyfile_name(validation, scope)
gc = gspread.authorize(credentials)
wks = gc.open_by_key(sheet_key).sheet1

#Function used in cleanups.py for send_to_pw_really.html
def send_to_sheet(data):
    #Rough draft of data
    #TODO: Match data format of Public Works
    timestamp = '{:%Y-%m-%d %H:%M:%S}'.format(datetime.datetime.now())
    data.insert(0,timestamp)
    print(data)
    wks.insert_row(data,index=top_row)

### CODE REVIEW

**Comment by howarddd** [comment]
Do I need to do something with our gce?

**Comment by TangoYankee** [comment]
Nah, I was trying to make a pull request on my branch and it went to yours
instead. One day, I'll figure out GitHub.

-Tim

**Comment by howarddd** [comment]
Yeah... that's both of us.

**Comment by TangoYankee** [comment]
Lo won't make it to Open Oakland tomorrow night. However, I would like to go and Lo is willing to conference and screenshare. Will you be going?
-Tim

Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: Howard D <notifications@github.com> Date: 7/10/17  00:01  (GMT-08:00) To: howarddd/TrashTalk <TrashTalk@noreply.github.com> Cc: TangoYankee <miller.tim108@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [howarddd/TrashTalk] google_sheets.py (#8) 
Yeah... that's both of us.





On Sun, Jul 9, 2017 at 6:01 PM, TangoYankee <notifications@github.com>

wrote:



> Nah, I was trying to make a pull request on my branch and it went to yours

> instead. One day, I'll figure out GitHub.

>

> -Tim

>

**Comment by howarddd** [comment]
If you are coming then I will ... but I may be a little late.   PLS
announce the project if I don't arrive before 7 pm.

I have a job that requires some afternoon and evening work.

**Pull request closed without merging**
